### ISSUE TITLE
No such file or directory: './latentspace/roomTypeDemo.json'

### ISSUE THREAD

**Issue by CharlieLei** [Shao-Kui/3DScenePlatform#24]
When I run main.py, it warns that

`Traceback (most recent call last):
  File "/home2/leicheng/3DScenePlatform/main.py", line 12, in <module>
    from autolayoutv2 import sceneSynthesis
  File "/home2/leicheng/3DScenePlatform/autolayoutv2.py", line 12, in <module>
    from projection2d import processGeo as p2d, connected_component, getobjCat
  File "/home2/leicheng/3DScenePlatform/projection2d.py", line 867, in <module>
    with open('./latentspace/roomTypeDemo.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: './latentspace/roomTypeDemo.json'`

How can I get this json file?

**Comment by Shao-Kui** [comment]
Hi @CharlieLei! I have just pushed an update for fixing dependencies. When pushing updates, we really have some undergoing works (unpublished works), so this may cause some dependency issues...Fortunately, the platform won't receive major updates at least in this year : )
